# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'records', '0001_initial'), (b'records', '0002_auto_20171028_2337'), (b'records', '0003_auto_20171029_0518'), (b'records', '0004_auto_20171029_0524'), (b'records', '0005_auto_20171029_0531'), (b'records', '0006_auto_20171029_0538'), (b'records', '0007_auto_20171029_1104')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('history_number', models.CharField(max_length=10, verbose_name='Number of History')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True, verbose_name='Gender')),
                ('weight', models.CharField(max_length=20, verbose_name='Weight')),
                ('length', models.CharField(max_length=20, verbose_name='Length')),
                ('path_to_file', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Record')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Middle Name')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hospital_number', models.CharField(max_length=10, verbose_name='Number of Hospital')),
                ('title', models.CharField(max_length=100, verbose_name='Name of Hospital')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital', verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital', verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FilePathField(blank=True, null=True, path=b'/work/virtualenvs/hearttone/src/hearttone/media', verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Record'),
        ),
    ]
