# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number_history', models.CharField(max_length=10, verbose_name='Number of History')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '\u0447\u043e\u043b\u043e\u0432\u0456\u0447\u0430'), (2, '\u0436\u0456\u043d\u043e\u0447\u0430')], null=True, verbose_name='\u0421\u0442\u0430\u0442\u044c')),
                ('weight', models.CharField(max_length=20, verbose_name='Weight')),
                ('length', models.CharField(max_length=20, verbose_name='Length')),
                ('path_to_file', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='\u041d\u043e\u0442\u0430\u0442\u043a\u0438')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
