# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_squashed_0007_auto_20171029_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='RecordPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=30, verbose_name='Start Time')),
                ('end_time', models.CharField(max_length=30, verbose_name='End Time')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number of Part')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'Part of Record',
                'verbose_name_plural': 'Parts of Records',
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='path_to_file',
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient', verbose_name='Patient'),
        ),
    ]
