# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Middle Name')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hospital_number', models.CharField(max_length=10, verbose_name='Number of Hospital')),
                ('title', models.CharField(max_length=100, verbose_name='Name of Hospital')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='number_history',
            new_name='history_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Record'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital', verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital', verbose_name='Hospital'),
        ),
    ]
