# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20171028_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FilePathField(blank=True, null=True, path=b'/work/virtualenvs/hearttone/src/hearttone/media', verbose_name='Record'),
        ),
    ]
