# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20171029_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='path_to_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Record'),
        ),
    ]
