# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20171112_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Notes'),
        ),
    ]
